### ISSUE TITLE
[1.8.9] Overchanter crash

### ISSUE THREAD

**Issue by Belgabor** [Modbder/ThaumicBases#38]
Crashes when you right-click with a wand to start upgrading.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 2/17/16 1:29 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: thaumcraft.common.lib.events.EssentiaHandler.drainEssentia(Lnet/minecraft/tileentity/TileEntity;Lthaumcraft/api/aspects/Aspect;Lnet/minecraft/util/EnumFacing;IZ)Z
    at tb.common.tile.TileOverchanter.func_73660_a(TileOverchanter.java:81)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at tb.common.tile.TileOverchanter.func_73660_a(TileOverchanter.java:81)

-- Block entity being ticked --
Details:
    Name: tb.overchanter // tb.common.tile.TileOverchanter
    Block type: ID #1007 (tile.overchanter // tb.common.block.BlockOverchanter)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-1125,64,30), Chunk: (at 11,4,14 in -71,1; contains blocks -1136,0,16 to -1121,255,31), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
    Actual block type: ID #1007 (tile.overchanter // tb.common.block.BlockOverchanter)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1716)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Belgabor'/83, l='MpServer', x=-1126.55, y=64.00, z=30.22]]
    Chunk stats: MultiplayerChunkCache: 625, 625
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -1120.00,4.00,10.00 - World: (-1120,4,10), Chunk: (at 0,0,10 in -70,0; contains blocks -1120,0,0 to -1105,255,15), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
    Level time: 317430 game time, 54045 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 52 total; [EntityVillager['Villager'/7, l='MpServer', x=-1200.31, y=65.00, z=33.22], EntityVillager['Villager'/8, l='MpServer', x=-1198.84, y=65.00, z=31.22], EntityVillager['Villager'/9, l='MpServer', x=-1199.72, y=65.00, z=40.88], EntityVillager['Villager'/10, l='MpServer', x=-1199.59, y=65.00, z=39.78], EntityVillager['Villager'/11, l='MpServer', x=-1204.28, y=64.00, z=38.44], EntityVillager['Villager'/12, l='MpServer', x=-1198.31, y=65.00, z=32.38], EntityVillager['Villager'/13, l='MpServer', x=-1198.31, y=65.00, z=33.38], EntityVillager['Villager'/14, l='MpServer', x=-1199.44, y=65.00, z=32.38], EntityAuraNode['Aura Node'/15, l='MpServer', x=-1192.50, y=66.50, z=169.50], EntityAuraNode['Aura Node'/16, l='MpServer', x=-1174.50, y=82.50, z=-47.50], EntityBat['Bat'/18, l='MpServer', x=-1136.66, y=40.10, z=43.13], EntityBat['Bat'/19, l='MpServer', x=-1136.53, y=40.10, z=38.13], EntityBat['Bat'/20, l='MpServer', x=-1139.53, y=39.10, z=33.88], EntityBat['Bat'/21, l='MpServer', x=-1141.47, y=39.10, z=33.84], EntityBat['Bat'/22, l='MpServer', x=-1139.19, y=39.10, z=38.06], EntityBat['Bat'/24726, l='MpServer', x=-1087.75, y=39.10, z=40.16], EntityBat['Bat'/23, l='MpServer', x=-1141.53, y=39.10, z=38.13], EntityBat['Bat'/24, l='MpServer', x=-1146.53, y=40.10, z=34.25], EntityBat['Bat'/25, l='MpServer', x=-1136.31, y=40.10, z=38.06], EntityBat['Bat'/26, l='MpServer', x=-1139.75, y=39.10, z=38.13], EntityAuraNode['Aura Node'/27, l='MpServer', x=-1128.50, y=66.50, z=-108.50], EntityBat['Bat'/28, l='MpServer', x=-1123.75, y=41.10, z=40.25], EntityBat['Bat'/29, l='MpServer', x=-1133.13, y=40.10, z=41.75], EntityPig['Pig'/31, l='MpServer', x=-1115.00, y=64.00, z=106.06], EntitySheep['Sheep'/32, l='MpServer', x=-1094.41, y=64.00, z=-34.69], EntitySheep['Sheep'/33, l='MpServer', x=-1092.16, y=64.00, z=-36.56], EntitySheep['Sheep'/34, l='MpServer', x=-1089.81, y=64.00, z=-37.84], EntityChicken['Chicken'/35, l='MpServer', x=-1089.44, y=64.00, z=-46.44], EntityAuraNode['Aura Node'/37, l='MpServer', x=-1098.50, y=36.50, z=35.50], EntityBat['Bat'/38, l='MpServer', x=-1088.88, y=38.10, z=36.75], EntitySheep['Sheep'/45, l='MpServer', x=-1080.81, y=64.00, z=-40.81], EntitySheep['Sheep'/46, l='MpServer', x=-1072.16, y=64.00, z=-41.66], EntityChicken['Chicken'/47, l='MpServer', x=-1073.66, y=64.00, z=-39.31], EntitySheep['Sheep'/48, l='MpServer', x=-1086.78, y=64.00, z=-47.66], EntityChicken['Chicken'/50, l='MpServer', x=-1076.59, y=64.00, z=-39.31], EntityItem['item.item.egg'/51, l='MpServer', x=-1079.56, y=64.00, z=-32.00], EntityMinecartChest['container.minecart'/52, l='MpServer', x=-1076.50, y=38.06, z=80.50], EntitySheep['Sheep'/56, l='MpServer', x=-1070.16, y=64.00, z=-48.66], EntitySquid['Squid'/57, l='MpServer', x=-1070.53, y=60.00, z=-3.50], EntityAuraNode['Aura Node'/58, l='MpServer', x=-1065.50, y=66.50, z=45.50], EntityMinecartChest['container.minecart'/59, l='MpServer', x=-1059.50, y=40.06, z=87.50], EntityAuraNode['Aura Node'/60, l='MpServer', x=-1054.50, y=65.50, z=-40.50], EntityAuraNode['Aura Node'/61, l='MpServer', x=-1054.50, y=65.50, z=22.50], EntityBat['Bat'/62, l='MpServer', x=-1056.72, y=39.10, z=54.94], EntityPlayerSP['Belgabor'/83, l='MpServer', x=-1126.55, y=64.00, z=30.22], EntityAuraNode['Aura Node'/63, l='MpServer', x=-1034.50, y=66.50, z=-38.50], EntityBat['Bat'/30275, l='MpServer', x=-1059.50, y=39.00, z=84.50], EntityAuraNode['Aura Node'/69, l='MpServer', x=-1011.50, y=66.50, z=106.50], EntityAuraNode['Aura Node'/70, l='MpServer', x=-1017.50, y=64.50, z=155.50], EntityAuraNode['Aura Node'/71, l='MpServer', x=-996.50, y=65.50, z=-15.50], EntityAuraNode['Aura Node'/72, l='MpServer', x=-1001.50, y=65.50, z=53.50], EntityAuraNode['Aura Node'/73, l='MpServer', x=-1001.50, y=92.50, z=164.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_71, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1743165592 bytes (1662 MB) / 3133997056 bytes (2988 MB) up to 4207738880 bytes (4012 MB)
    JVM Flags: 13 total; -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx4096m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1734 77 mods loaded, 77 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1734-universal.jar) 
    UCHIJAAAA   Forge{11.15.1.1734} [Minecraft Forge] (forge-1.8.9-11.15.1.1734-universal.jar) 
    UCHIJAAAA   bowinfinityfix{rv2} [Bow Infinity Fix] (minecraft.jar) 
    UCHIJAAAA   additionalbanners{1.1.1} [Additional Banners] (AdditionalBanners-1.1.1-1.8.9.jar) 
    UCHIJAAAA   AppleCore{1.3.0} [AppleCore] (AppleCore-mc1.8.9-1.3.0.jar) 
    UCHIJAAAA   BuildersGuides{1.8.9-0.1.0-alpha} [Builder's Guides] (buildersguides-1.8.9-0.1.0-alpha.jar) 
    UCHIJAAAA   Chameleon{1.8.9-0.2.1} [Chameleon] (Chameleon-1.8.9-0.2.1.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.1.jar) 
    UCHIJAAAA   mcmultipart{1.0.6} [MCMultiPart] (MCMultiPart-1.0.6-universal.jar) 
    UCHIJAAAA   chiselsandbits{mc1.8.9-v1.8.10} [Chisels & Bits] (chiselsandbits-mc1.8.9-v1.8.10.jar) 
    UCHIJAAAA   compasscoords{1.8.9-0.2.6} [Compass Co-ords] (CompassCoords-1.8.9-0.2.6.jar) 
    UCHIJAAAA   craftingcraft{2.0.11} [CraftingCraft] (craftingcraft-mc1.8.9-2.0.11.jar) 
    UCHIJAAAA   craftingtweaks{3.0.41} [Crafting Tweaks] (craftingtweaks-mc1.8.9-3.0.41.jar) 
    UCHIJAAAA   craftingtweaksaddons{1.0} [Crafting Tweaks Addons] (craftingtweaksaddons-mc1.8.9-3.0.8.jar) 
    UCHIJAAAA   CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
    UCHIJAAAA   lootablebodies{1.4.1} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.1.jar) 
    UCHIJAAAA   DeathCounter{5.0.0} [DeathCounter] (DeathCounter-MC1.8.9.jar) 
    UCHIJAAAA   DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0.jar) 
    UCHIJAAAA   EnderZoo{1.8.9-1.1.0} [Ender Zoo] (EnderZoo-1.8.9-1.1.2.jar) 
    UCHIJAAAA   ExtraBitManipulation{1.8.9-1.3.3} [Extra Bit Manipulation] (ExtraBitManipulation-1.8.9-1.3.3.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.3} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.6.jar) 
    UCHIJAAAA   fe{1.1} [Food Expansion] (FoodExpansion1.1-mc1.8.9.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
    UCHIJAAAA   FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
    UCHIJAAAA   gearswap{1.2.4} [Gear Swapper] (gearswap-1.8.9-1.2.4.jar) 
    UCHIJAAAA   Harvest{1.8.9-1.0.0-2} [Harvest] (Harvest-1.8.9-1.0.0-2.jar) 
    UCHIJAAAA   HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12.jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
    UCHIJAAAA   InGameInfoXML{2.8.1.80} [InGame Info XML] (InGameInfoXML-1.8.9-2.8.1.80-universal.jar) 
    UCHIJAAAA   intangible{0.0.21} [Intangible] (intangible-1.8.9-0.0.21.jar) 
    UCHIJAAAA   InventoryCenterer{1.8.9-0.1.1} [Inventory Centerer] (InventoryCenterer-1.8.9-0.1.1.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks] (InventoryTweaks-1.60-beta-30.jar) 
    UCHIJAAAA   ironbackpacks{1.8-1.0.7} [Iron Backpacks] (IronBackpacks-1.8-1.0.7.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.25.11.150} [Just Enough Items] (jei_1.8.9-2.25.11.150.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft] (Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons] (JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources] (JustEnoughResources-1.8.9-0.3.1.jar) 
    UCHIJAAAA   jwin{univ_compat_filler} [Just What I Needed] (JWIN_v0.11.1_1.8.9.jar) 
    UCHIJAAAA   k4lib{1.8.9-1.0.14} [K4Lib] (k4lib-1.8.9-1.0.14-universal.jar) 
    UCHIJAAAA   Login_Shield_MC1.8.9{1.2-16-gd25a704} [Login Shield] (Login_Shield_MC1.8.9-1.2-16-gd25a704.jar) 
    UCHIJAAAA   missing_pieces{1.4.0} [Missing Pieces] (missingPieces-1.8.9-1.4.0.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   moarsigns{2.0.0} [MoarSigns] (MoarSigns-1.8.9-2.0.0.jar) 
    UCHIJAAAA   ModNameTooltip{1.0.0} [Mod Name Tooltip] (modnametooltip_1.8.8-1.0.0.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAA   Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
    UCHIJAAAA   MouseTweaks{2.6.0} [Mouse Tweaks] (MouseTweaks-2.6.0-mc1.8.9.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.1-2.jar) 
    UCHIJAAAA   samsocean{1.0.0} [Classic Oceans] (OceanFloor-1.8.9-1.0.0.jar) 
    UCHIJAAAA   clayspawn{1.8.9a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.8.9a.jar) 
    UCHIJAAAA   pandp{0.1.2} [Parcels and Packages] (Parcels_And_Packages-0.1.2_HOTFIX.jar) 
    UCHIJAAAA   playerrugs{0.0.1} [Player Rugs] (PlayerRugs-1.8.8-1.2.0.jar) 
    UCHIJAAAA   Psi{beta-11} [Psi] (Psi-beta-11.jar) 
    UCHIJAAAA   psiproducts{1.0.0} [Psi Dot Products] (PsiProducts-1.0.0.jar) 
    UCHIJAAAA   PvpToggle{1.8.9-1.0.11} [PVP Toggle] (pvpToggle-1.8.9-1.0.11-universal.jar) 
    UCHIJAAAA   ReAuth{2.1} [ReAuth] (ReAuth-2.1-1.8.jar) 
    UCHIJAAAA   reborncore{1.4.1.15} [RebornCore] (RebornCore-1.8.9-1.4.1.15-universal.jar) 
    UCHIJAAAA   RecipeTooltips{1.1.24} [RecipeTooltips] (RecipeTooltips-1.8.9-1.1.24.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
    UCHIJAAAA   rightclicktorch{1.8.9-1.0.2} [RightClickTorch] (rightclicktorch-1.8.9-1.0.2.jar) 
    UCHIJAAAA   Schematica{1.7.7.143} [Schematica] (Schematica-1.8.9-1.7.7.143-universal.jar) 
    UCHIJAAAA   SilentGems{1.3.9b} [Silent's Gems] (SilentsGems-1.8.9-1.3.9b-102.jar) 
    UCHIJAAAA   sodacanutils{2.0.4} [Sodacan Utilities] (sodacanutils-2.0.4.jar) 
    UCHIJAAAA   spawnchecker{2.3-SNAPSHOT} [SpawnChecker] (SpawnChecker-2.3-SNAPSHOT.jar) 
    UCHIJAAAA   spawnchecker.presetmode{2.3-SNAPSHOT} [SpawnChecker preset mode] (SpawnChecker-2.3-SNAPSHOT.jar) 
    UCHIJAAAA   StorageDrawers{1.8.9-2.3.4} [Storage Drawers] (StorageDrawers-1.8.9-2.3.4.jar) 
    UCHIJAAAA   thaumicbases{1.4.189.23} [Thaumic Bases] (ThaumicBases-2.1.189.23.jar) 
    UCHIJAAAA   thaumicinfusion{4.78} [Thaumic Infusion] (ThaumicInfusion-1.8.9-4.78.jar) 
    UCHIJAAAA   Trashcans{1.0.0} [Trashcans] (Trashcans-1.8.9-1.0.0.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
    UCHIJAAAA   Whitelister{0.2.35} [Whitelister] (Whitelister-1.8.9-0.2.35.jar) 
    Loaded coremods (and transformers): 
thaumicinfusion (ThaumicInfusion-1.8.9-4.78.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
BIFLoader (BowInfinityFix-1.8.x-rv2.jar)
  com.github.parker8283.bif.Transformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GTX 970/PCIe/SSE2'
    [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore''Thaumic Infusion'
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.75, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x AMD FX(tm)-8120 Eight-Core Processor 
```

**Comment by Modbder** [comment]
Fixed.
