### ISSUE TITLE
Incompatible with Mekanism and Factorization

### ISSUE THREAD

**Issue by HakureiNyaruko** [Modbder/ThaumicBases#6]
Crash on startup :(

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15-7-30 3:37
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 3
	at tb.common.itemblock.ItemBlockTBLogs.func_77667_c(ItemBlockTBLogs.java:17)
	at mekanism.api.util.StackUtils.hashItemStack(StackUtils.java:250)
	at mekanism.common.recipe.inputs.ItemStackInput.hashIngredients(ItemStackInput.java:60)
	at mekanism.common.recipe.inputs.MachineInput.hashCode(MachineInput.java:28)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:581)
	at mekanism.common.recipe.RecipeHandler.addRecipe(RecipeHandler.java:65)
	at mekanism.common.recipe.RecipeHandler.addPrecisionSawmillRecipe(RecipeHandler.java:186)
	at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:364)
	at mekanism.common.integration.OreDictManager.init(OreDictManager.java:38)
	at mekanism.common.Mekanism.postInit(Mekanism.java:1245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by Modbder** [comment]
Try the latest build of the mod from curse - the issue might have been fixed, if there was nothing more to it than just this crash. Might not be the case - then I'll need the new crash report.

**Comment by HakureiNyaruko** [comment]
I've been updated, and crash again.http://pastebin.com/LcnCNNcZ

**Comment by Modbder** [comment]
Don't you mind me giving you different test builds right here, in this issue then? It takes some time for the curse to update the project...

**Comment by Modbder** [comment]
Try out this build, might be just me messing the numbers up...
http://www.mediafire.com/download/jh2eobe25q4j2np/ThaumicBases-1.2.1710.12.jar

**Comment by HakureiNyaruko** [comment]
yea, it's fixed.
thanks a lot! :D
